// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: emp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Department string  `protobuf:"bytes,3,opt,name=Department,proto3" json:"Department,omitempty"`
	Salary     float32 `protobuf:"fixed32,4,opt,name=Salary,proto3" json:"Salary,omitempty"`
}

func (x *Emp) Reset() {
	*x = Emp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emp) ProtoMessage() {}

func (x *Emp) ProtoReflect() protoreflect.Message {
	mi := &file_emp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emp.ProtoReflect.Descriptor instead.
func (*Emp) Descriptor() ([]byte, []int) {
	return file_emp_proto_rawDescGZIP(), []int{0}
}

func (x *Emp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Emp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emp) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Emp) GetSalary() float32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

type EmpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Empdata *Emp `protobuf:"bytes,1,opt,name=empdata,proto3" json:"empdata,omitempty"`
}

func (x *EmpRequest) Reset() {
	*x = EmpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpRequest) ProtoMessage() {}

func (x *EmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpRequest.ProtoReflect.Descriptor instead.
func (*EmpRequest) Descriptor() ([]byte, []int) {
	return file_emp_proto_rawDescGZIP(), []int{1}
}

func (x *EmpRequest) GetEmpdata() *Emp {
	if x != nil {
		return x.Empdata
	}
	return nil
}

type EmpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Emp `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EmpResponse) Reset() {
	*x = EmpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpResponse) ProtoMessage() {}

func (x *EmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpResponse.ProtoReflect.Descriptor instead.
func (*EmpResponse) Descriptor() ([]byte, []int) {
	return file_emp_proto_rawDescGZIP(), []int{2}
}

func (x *EmpResponse) GetResult() *Emp {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_emp_proto protoreflect.FileDescriptor

var file_emp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x61, 0x0a, 0x03, 0x45, 0x6d,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x53, 0x61, 0x6c, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x0a,
	0x0a, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x65,
	0x6d, 0x70, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70,
	0x52, 0x07, 0x65, 0x6d, 0x70, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x0b, 0x45, 0x6d, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x32, 0x55, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x47, 0x0a, 0x08, 0x42, 0x69, 0x64, 0x69, 0x5f, 0x45, 0x6d, 0x70, 0x12, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emp_proto_rawDescOnce sync.Once
	file_emp_proto_rawDescData = file_emp_proto_rawDesc
)

func file_emp_proto_rawDescGZIP() []byte {
	file_emp_proto_rawDescOnce.Do(func() {
		file_emp_proto_rawDescData = protoimpl.X.CompressGZIP(file_emp_proto_rawDescData)
	})
	return file_emp_proto_rawDescData
}

var file_emp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_emp_proto_goTypes = []interface{}{
	(*Emp)(nil),         // 0: grpc_services.Emp
	(*EmpRequest)(nil),  // 1: grpc_services.EmpRequest
	(*EmpResponse)(nil), // 2: grpc_services.EmpResponse
}
var file_emp_proto_depIdxs = []int32{
	0, // 0: grpc_services.EmpRequest.empdata:type_name -> grpc_services.Emp
	0, // 1: grpc_services.EmpResponse.result:type_name -> grpc_services.Emp
	1, // 2: grpc_services.EmpService.Bidi_Emp:input_type -> grpc_services.EmpRequest
	2, // 3: grpc_services.EmpService.Bidi_Emp:output_type -> grpc_services.EmpResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_emp_proto_init() }
func file_emp_proto_init() {
	if File_emp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emp_proto_goTypes,
		DependencyIndexes: file_emp_proto_depIdxs,
		MessageInfos:      file_emp_proto_msgTypes,
	}.Build()
	File_emp_proto = out.File
	file_emp_proto_rawDesc = nil
	file_emp_proto_goTypes = nil
	file_emp_proto_depIdxs = nil
}
